### ISSUE TITLE
How to work with Bloc?

### ISSUE THREAD

**Issue by jinfagang** [themadmrj/chat_ui_kit#13] opened 2021-04-07 15:03 UTC
Hi, take your example code as example:

```dart
return ChatsList(
        chatsListStyle: ChatsListStyle(physics: BouncingScrollPhysics()),
        controller: _model.controller,
        appUserId: _model.localUser.id,
        scrollHandler: handleScrollEvent,
        groupAvatarStyle: GroupAvatarStyle(
            withSeparator: false,
            separatorColor: Colors.white,
            mode: GroupAvatarMode.aligned),
        builders: ChatsListTileBuilders(
            groupAvatarBuilder: (context, imageIndex, itemIndex, size, item) {
              final chat = item as ChatWithMembers;
              return Image.asset(chat.membersWithoutSelf[imageIndex].avatar,
                  width: size.width, height: size.height, fit: BoxFit.cover);
            },
            lastMessageBuilder: _buildLastMessage,
            wrapper: _buildTileWrapper,
            dateBuilder: (context, date) => Padding(
                padding: EdgeInsets.only(left: 16),
                child: Text(DateFormatter.getVerboseDateTimeRepresentation(
                    context, date)))),
        areItemsTheSame: (ChatBase oldItem, ChatBase newItem) =>
            oldItem.id == newItem.id);
```

the chats is controlled inside `        controller: _model.controller,` right? Then my question is, how to make it work with bloc stream?

I mean, typically using a `StreamBuilder` and a stream from my bloc to feed data into this controller, is there way to make this happen?

**Comment by themadmrj** [comment] 2021-04-07 15:19
Bloc, MVP, MVVM... it doesn't matter all patterns exist just to separate logic from UI and make it reusable. Using a stream, why don't you just use `stream.listen ((List<ChatBase> chats) { controller.addAll(chats); } );`? I don't get where the problem is. You just don't use a `StreamBuilder` here, instead the controller will rebuild `ChatsList` as needed.

**Comment by jinfagang** [comment] 2021-04-08 03:57
@themadmrj Hi, thanks for your reply. I am not really have experiences on using stream.listen. Here is my puzzels:

1) `stream.listen` where place it? Do u have an example?
2) I want UI updated once stream updated. If using `stream.listen`, will UI update?

**Comment by themadmrj** [comment] 2021-04-08 09:15
1. Check the [documentation ](https://api.dart.dev/stable/2.12.2/dart-async/Stream/listen.html) for explanations about streams & streamSubscriptions.
2. Yes obviously. Each time you call a method from `controller`, the UI will update accordingly.

**Comment by jinfagang** [comment] 2021-04-08 09:24
@themadmrj I know a little about streams, I want ask is: is it place into initState func or build func?

**Comment by themadmrj** [comment] 2021-04-08 09:28
Except in some very rare cases, you should never call methods that trigger rebuilds inside `build()`, since according to the docs, `build` may be called anytime, which means you do not have full control over it.

**Comment by jinfagang** [comment] 2021-04-08 10:27
@themadmrj thank u sir. I still have one unrelated question:

we have chats screen and detailed chat screen. As for a realtime chat application, the messages will become more and more, meanwhile when you come back from detail chat screen to chats screen, your chats screen should also update.

So, what is the best way to stores the messages? In your example, you using a fake data class, But in real app, should I share the bloc between chats and chat detail? So that I can update messages as well as chats screen's _controller to update chats?

**Comment by themadmrj** [comment] 2021-04-08 11:05
Well yes obviously. When a new messages arrives and you are in the chat itself, both the chat and ChatsList should receive the messages in order to update themselves. The typical way to do that is using [ChangeNotifier](https://api.flutter.dev/flutter/foundation/ChangeNotifier-class.html). I personnally use a migrated version of [PropertyChangeNotifier](https://pub.dev/packages/property_change_notifier).

I am now closing this topic and please for help about how to proceed regarding development, visit StackOverflow. Only post here if you have troubles with the library itself.

**Closed by themadmrj** 2021-04-08 11:05 UTC
