### ISSUE TITLE
ChatsList don't like listview behavior

### ISSUE THREAD

**Issue by jinfagang** [themadmrj/chat_ui_kit#25] opened 2021-05-14 15:35 UTC
this is normal ListView:

![image](https://user-images.githubusercontent.com/21303438/118293671-76a9b300-b50c-11eb-84ab-078e8890d9e1.png)

this is ChatsList
![image](https://user-images.githubusercontent.com/21303438/118293747-8de8a080-b50c-11eb-896a-9a8cca52295b.png)

Hi, I am not here report a bug or problem of this package. On the opposite using this lib I managed to build a useful chat App. 

But I found a slightly bias behavior might not notice by you. As you can see, when the List scroll to the bottom, ChatsList can not handle with the bottomBar, while ListView can handle,  **on the other words, ListView the last item will not blind by the navigationBar, this can be notice easily if your bottomBar blurred**.

Is there a way to replace ChatsList with ListView while also preserve all other features? I really don't know why they behavior such bias

**Comment by themadmrj** [comment] 2021-05-14 16:28
> Hi, I am not here report a bug or problem of this package. On the opposite using this lib I managed to build a useful chat App.

There is nothing wrong with reporting a bug. On the contrary, reporting a bug leads to a better library!

Can you please post the full code for both cases? If possible, a working minimal app would be good. I have to test it myself, because ChatsList is just an AnimatedListView, which means the behaviour regarding layout is the same.

**Comment by jinfagang** [comment] 2021-05-16 11:13
@themadmrj  thanks for your detailed analysis. I shall test your code first.


> -when would you want to use a blurring effect? When you want to see the content behind the blurring layer, which therefore has to OVERLAP said content

I am using a custom bottom navbar, which from this lib: https://github.com/rickywen911/custom_bubble_navigation_bar
I am using it because of it's effect seems nice, and with some default animations original doesn't provided. Hope this info provides more detail. However, the original ListView can handle with this navbar, (the last item will not blinded).

> -thus, it is actually expected to see the last chat item behind you bottomBar, in a stacked way
Which means there would be nothing wrong in your pictures.

It's true, for blurred effect, needs stacked way so that content can viewed on the behind of navbar. But problems is, the last item, can not jump above the navbar and stucked at the very bottom.

**Comment by jinfagang** [comment] 2021-05-16 11:19
@themadmrj  Oh, I just realise the difference:

THe exmple provided, it doesn't have any content behind navbar. so it shouldn't have my problem. My problem mainly is **content is fullscreen, and the last item can not jump above navbar**.

I paste some code hope it's not too messy:

```dart

Scaffold(
            extendBody: true,
            // backgroundColor: Colors.red,
            // backgroundColor: Colors.transparent,
            backgroundColor: Theme.of(context).dialogBackgroundColor,
            appBar: PreferredSize(
                preferredSize: const Size(double.infinity, kToolbarHeight),
                child: getNavBar(_homeBloc, _chatBloc)),
            bottomNavigationBar: CustomNavigationBar(
              // iconSize: 30.0,
              selectedColor: COLOR_PRIMARY_APP,
              strokeColor: COLOR_PRIMARY_APP.withAlpha(70),
              bubbleCurve: Curves.bounceInOut,
              unSelectedColor: Colors.grey[600],
              backgroundColor: Theme.of(context).dialogBackgroundColor,
              borderRadius: Radius.circular(16.0),
              blurEffect: true,
              opacity: 0.7,
              items: [
                CustomNavigationBarItem(
                  icon: Icon(FluentIcons.chat_24_filled),
                ),
                CustomNavigationBarItem(
                  icon: Icon(
                    FluentIcons.contact_card_24_filled,
                  ),
                ),
                CustomNavigationBarItem(
                  icon: Icon(
                    FluentIcons.lightbulb_24_filled,
                  ),
                ),
              ],
              currentIndex: _currentIndex,
              onTap: (index) {
                HapticFeedback.lightImpact();
                _homeBloc.setIndex(index);
                print('crtIndex;;;;; $index');
                setState(() {
                  _currentIndex = index;
                });
              },
              isFloating: true,
            ),
            // bottomNavigationBar: BottomNavigationBar(
            //   // iconSize: 30.0,
            //   // selectedColor: COLOR_PRIMARY_APP,
            //   // strokeColor: Colors.red,
            //   // unSelectedColor: Colors.grey[600],
            //   backgroundColor: Colors.white,
            //   // borderRadius: Radius.circular(16.0),
            //   // blurEffect: true,
            //   // opacity: 0.6,
            //   items: [
            //     BottomNavigationBarItem(
            //         icon: Icon(FluentIcons.chat_24_filled), label: "aaa"),
            //     BottomNavigationBarItem(
            //         icon: Icon(
            //           FluentIcons.contact_card_24_filled,
            //         ),
            //         label: "aaa"),
            //     BottomNavigationBarItem(
            //         icon: Icon(
            //           FluentIcons.lightbulb_24_filled,
            //         ),
            //         label: "aaa"),
            //   ],
            //   currentIndex: _currentIndex,
            //   onTap: (index) {
            //     setState(() {
            //       _currentIndex = index;
            // });
            // },
            // isFloating: true,
            // ),
            body: contactsPage);
```

Here is using `            extendBody: true,`

And contactsPage with:

```dart
@override
  Widget build(BuildContext context) {
    ContactBloc contactBloc = new ContactBloc();

    HomeBloc homeBloc = BlocProvider.of(context);
    homeBloc.setIndex(1);

    return StreamBuilder(
        stream: contactBloc.contactsStream,
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            List<Contact> cs = snapshot.data;
            return ListView.builder(
                itemCount: cs.length,
                itemBuilder: (context, i) {
                  return Column(children: <Widget>[
                    _buildContactRow(cs[i]),
                    Divider(
                        indent: 32, height: 1, color: Colors.grey.withAlpha(20))
                  ]);
                });
          } else {
            return SpinKitFadingCircle(
              color: COLOR_PRIMARY_APP,
            );
          }
        });
  }

```

contactsPage only is a ListView.  It can solve with last item. But same main page scafffold, using ChatsLists, there will blind the last item.

**Comment by themadmrj** [comment] 2021-05-29 21:08
Indeed, it is as you say, the last item will not move above the navbar. Sadly I cannot help you with this specific usecase. As you can see, `chat_ui_kit` uses `ImplicitlyAnimatedList`, which is an external library. Therefore, your problem has to do with `ImplicitlyAnimatedList` and not really `chat_ui_kit`. I encourage you to open a bug report on their library. What I usually do in such specific cases, is debug it myself by changing the libs until I found the problem and then submit a PR.
Closing for now, as it is not a bug originating from `chat_ui_kit`.

**Closed by themadmrj** 2021-05-29 21:08 UTC

**Comment by jinfagang** [comment] 2021-05-30 08:17
thanks, I have posted an issue to that lib:

https://github.com/bnxm/implicitly_animated_reorderable_list/issues/77
